# where to store uploaded images and session files
UPLOAD_FOLDER = "/tmp/"
SESSION_FOLDER = "/tmp/"

# serve the upload folder via http with no authentication
INSECURE_DOWNLOAD = false

# white-list of allowed senders (email and social accounts)
SENDERS = ['Camera@samsungcamera.com']

# CHANGE THIS! hmac256 mangle sender addresses into folders with this secret
SECRET = "xiev5kaMeehaimub"

# Email configuration: SMTP smarthost
MAIL_SERVER = 'CHANGEME'
MAIL_PORT = 587
MAIL_USERNAME = 'username'
MAIL_PASSWORD = 'password'
MAIL_USE_TLS = true

# Mastodon configuration
[MASTODON]
# if `TOKEN` is a file created by mastodonlogin.py, `BASE_URL` is not needed
#BASE_URL = ''
TOKEN = 'mastodon.secret'
POSTSCRIPT = ' #photography #SamsungNX'
VISIBILITY = 'unlisted' # 'direct', 'private', 'unlisted', 'public'

# example instance config overriding only the visibility
[MASTODON.pub]
VISIBILITY = 'public'

# example shell command not using stdin
[SHELL]
CMD = [ "./log.sh", "{sender}", "{recipient}", "{filename}" ]

# example shell command extending the default `SHELL` action with stdin
[SHELL.log]
STDIN = """From: {sender}
To: {recipient}
Subject: {subject}

{filename}

{body}
."""

# Override the default actions with alternatives (store, mastodon, shell, drop)
# and optional instances
[ACTIONS]
facebook = "mastodon" # will post using the [MASTODON] config
picasa = "store" # store into `$UPLOAD_FOLDER/$mangled_picasa_login`
"masto@mydomain.com" = "mastodon" # will post using the [MASTODON] config
"masto-public@mydomain.com" = "mastodon.pub" # will post using [MASTODON.pub]
"store@mydomain.com" = "store.mailfolder" # will store into `$UPLOAD_FOLDER/mailfolder`
"drop@mydomain.com" = "drop" # will not store/send
