# where to store uploaded images
UPLOAD_FOLDER = "/tmp/"

# serve the upload folder via http
INSECURE_DOWNLOAD = false

# white-list of allowed senders
SENDERS = ['Camera@samsungcamera.com']

# CHANGE THIS! hmac256 mangle sender addresses into folders with this secret
SECRET = "xiev5kaMeehaimub"

# Email configuration
MAIL_SERVER = 'CHANGEME'
MAIL_PORT = 587
MAIL_USERNAME = 'username'
MAIL_PASSWORD = 'password'
MAIL_USE_TLS = true

